### ISSUE TITLE
possibility to allow changing the .cache folder path

### ISSUE THREAD

**Issue by borauyar** [federicomarini/HCAData#2]
Hi, 

`HCAData::HCAData` function currently does not allow setting a different .cache folder for the downloaded datasets. It would be great if it was allowed to pass an alternative cache folder to the `ExperimentHub::ExperimentHub` function. 

Thanks!

**Comment by federicomarini** [comment]
Hi Bora,
I think that can be configured directly when using `ExperimentHub`. I think some relevant info are contained in `?getExperimentHubOption`.

So basically this would mean you can set the cache folder in the same way as for `EH`.

I am pinging in @lshep which might have also some explanation on the reason for keeping one single location for all the caches - my guess would just be the simplicity of the one location.
Federico

**Comment by lshep** [comment]
We keep a single cache location for easier management of files.  For use inside packages, BiocFileCache and ExperimentHub can allow for alternative locations but we leave that up to the developer or the end user.   
@federicomarini  is correct.  There are two ways to change the default location setting of ExperimentHub.   One is through the `setExperimentHubOption` that should be called before the call to `ExperimentHub` so in this case before running `HCAData`.   The call would be something similar to 
`setExperimentHubOption("CACHE",  <newpathlocation>) `.   The other option if you want to permanently move your cache location for all runnings of ExperimentHub, or an alternative for a single session depending on how you set it,   There is a system environment variable   `EXPERIMENT_HUB_CACHE` .  If this is exported and found on your system, this will be used for the default location.  
Hope this helps.

**Comment by federicomarini** [comment]
It did help Lori, thanks a lot!

@borauyar would it be enough for you to specify the location of the cache in advance - I guess only for files you would retrieve here?

**Comment by borauyar** [comment]
@federicomarini @lshep thanks a lot for both of your answers!

**Comment by federicomarini** [comment]
You're welcome!
Closing this, in case something should be left to clarify drop me a message 😉
