### ISSUE TITLE
Add a sparse= switch to all HDF5Array constructors

### ISSUE THREAD

**Issue by LTLA** [federicomarini/HCAData#4]
See Bioconductor/DelayedArray#82 for the speed improvements. I suggest the getters all have an `as.sparse=` option, defaulting to `FALSE` for the time being but to be flipped to `TRUE` once we've put it through its paces (e.g., in the book).

**Comment by federicomarini** [comment]
Thank you Aaron for pointing this out!

**Comment by LTLA** [comment]
So, is this going to happen, or what?

**Comment by federicomarini** [comment]
Yup 😉 
Been just v busy for the EuroBioc setup, and for wrapping up things before Christmas.
It is on the todo list, so it won't be forgotten (and even #googledown won't affect that)

**Comment by LTLA** [comment]
Looks good on my end. Happy for you to close if you push to BioC.

**Comment by LTLA** [comment]
Also suggest setting the default to `TRUE`; the sparse DA infrastructure seems reliable enough in BioC-devel.

**Comment by federicomarini** [comment]
Done & Done, thank you for the checks!
Pushed upstream now & closing
